CREATE TABLE [dbo].[marcavehiculo]
(
	MarcaVehiculoID INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_MarcaVehiculo PRIMARY KEY CLUSTERED (MarcaVehiculoID)
 ,  Descripcion VARCHAR(250) NOT NULL
 ,  Estado BIT NOT NULL
)
WITH (DATA_COMPRESSION=PAGE)
GO


